name: Hello world

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-24.04
    steps:
      - name: Dire Bonjour
        run: echo "Hello, Github Actions!"

      - name: Afficher les infos du contexte
        run: |
          echo "Repository: \${{ github.repository }}"
          echo "Branche: \${{ github.ref_name }}"
          echo "Auteur: \${{ github.actor }}"
